### ISSUE TITLE
开发者修改了Notion模版导致老模版用户同步失败

### ISSUE THREAD

**Issue by anuxs** [malinkang/weread2notion#14]
问题：
notion_client.errors.APIResponseError: ISBN is not a property that exists. URL is not a property that exists. Rating is not a property that exists.

原因：
拥有老模版的用户，因为缺少新增的：ISBN URL Rating  三个字段，

解决方案：
需要自己手工该模版添加属性，或者删除模版重新导入模版重新同步。

**Comment by hprandom** [comment]
我添加了这3个字段，可以同步了。

可为啥这3个字段还是空白的？那添加了做什么……

**Comment by malinkang** [comment]
需要删掉全部的笔记再全量同步一遍。因为每次都不会全量同步的，耗时比较长。

**Comment by hprandom** [comment]
增量同步也挺好，可以看看自己装了这个工具后，看了几本书。
