### ISSUE TITLE
自动运行成功后notion内容没有发生改变

### ISSUE THREAD

**Issue by feuferoce** [malinkang/weread2notion#40]
第一次发生时我直接删了原来的，重新建了一个，但是后来建的第二个还是发生这种情况，于是我将Cookie和NotionDatabaseID给替换了，然后我手动运行了一次，成功了，请问如何避免下次遇到这种情况？

**Comment by malinkang** [comment]
看看报错没，有报错的话提供下报错信息。

**Comment by feuferoce** [comment]
第一次修改后运行失败，图片如下。
之后运行都是成功的，但是除了第一次成功后修复成功了，notion内容改变后，之后我又添加了一些内容，但是手动运行后，notion依旧没有替换新的内容上去。
<img width="537" alt="屏幕截图 2023-11-21 174203" src="https://github.com/malinkang/weread2notion/assets/149480367/201fde92-96cc-4f47-8761-39479fd69941">
<img width="530" alt="屏幕截图 2023-11-21 174111" src="https://github.com/malinkang/weread2notion/assets/149480367/f2c75194-02dc-4c7d-b6c2-56b19745832a">

**Comment by malinkang** [comment]
嗯，看了下项目确实存在bug，目前已经修复了。
