### ISSUE TITLE
无法实现任务自动执行

### ISSUE THREAD

**Issue by frednefu** [malinkang/weread2notion#41]
我的手动执行都好使，为啥自动执行无效，每天0点不执行，改成0/5 * * * *，每5分钟执行一次也是无效，是否还有啥地方配置自动执行的操作。

**Comment by malinkang** [comment]
https://docs.github.com/zh/actions/using-workflows/events-that-trigger-workflows#schedule 看看这个吧。你改成这个应该是每小时的0分和5分执行，不如10点执行一次，10点5分执行一次，不是5分钟执行一次。给个star吧。不能总白嫖😄
