### ISSUE TITLE
同步失败，请问怎么解决

### ISSUE THREAD

**Issue by 1716285375** [malinkang/weread2notion#67]
![image](https://github.com/malinkang/weread2notion/assets/58598906/aff2a9f5-633f-4eb9-83a5-2d96bab2ef71)

**Comment by 1716285375** [comment]
已解决，问题原因：微信阅读cookie过期

**Comment by xiaola233** [comment]
咋整的

**Comment by Xavier1027** [comment]
把微信读书的Cookie查新填一下

**Comment by qwer2479** [comment]
> 已解决，问题原因：微信阅读cookie过期。解决方法：更新微信阅读cookie。

请问cookie大概多久会失效？
